# Generated by Django 6.0.7 on 2026-08-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crime',
            name='crime_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crime',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Under Investigation', 'Under Investigation'), ('Solved', 'Solved')], default='Pending', max_length=50),
        ),
    ]
