# Generated by Django 6.0.7 on 2026-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crime_user_alter_crime_crime_type_alter_crime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_type',
            field=models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Fraud', 'Fraud'), ('Cyber Crime', 'Cyber Crime'), ('Other', 'Other')], max_length=100),
        ),
    ]
