# Generated by Django 6.0.7 on 2026-08-05 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crime_crime_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='user',
        ),
        migrations.AddField(
            model_name='crime',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crimes_reported', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crime',
            name='crime_type',
            field=models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Fraud', 'Fraud'), ('Cyber Crime', 'Cyber Crime'), ('Other', 'Other')], max_length=50),
        ),
    ]
