# Generated by Django 6.0.7 on 2026-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_crime_user_crime_reported_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Solved', 'Solved')], default='Pending', max_length=50),
        ),
    ]
