# Generated by Django 6.0.7 on 2026-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_crime_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='crime+photos/'),
        ),
    ]
